### ISSUE TITLE
Game directory not found

### ISSUE THREAD

**Issue by roctobre** [RedFox20/PackFileManager#1]
Hello,

v5.1 starts with an error - Game Directory not found.
gamedirs.txt contains the correct paths for Rome2 and Attila.

gamedirs.txt:

TWH2;
TWH;
ATW;S:\Spiele\Steam\steamapps\common\Total War Attila
R2TW;S:\Spiele\Steam\steamapps\common\Total War Rome II
STW;
NTW;
ETW;

**Comment by RedFox20** [comment]
Hello @roctobre,

Thank you for submitting this bug report. Do you get the same error if you delete gamedirs.txt?

I added an additional set of checks to PFM - now it makes sure the "data" folder also exists while automatically detecting the game folders:
https://github.com/RedFox20/PackFileManager/commit/c1b095b113209c12764afb93a2edf7ce3ff67831

Are you compiling PFM 5.1 directly from the .NET solution? I haven't made a public release of this due to lack of interest yet 😄

**Comment by roctobre** [comment]
I get the same error when i delete gamedirs.txt.
I got your source code an ran it through VisualStudio. Maybe something went wrong here.
With your latest changes it doesnt work also.

**Comment by roctobre** [comment]
![grafik](https://user-images.githubusercontent.com/36789094/36643783-9ddd5954-1a50-11e8-839e-aef665e7d4d2.png)

![grafik](https://user-images.githubusercontent.com/36789094/36643804-c0fb8e92-1a50-11e8-8213-863f0535fd80.png)

**Comment by RedFox20** [comment]
I think it's setting `CurrentGame` to a game value from app settings, even though that game is invalid. Definitely a bug that can be fixed 👍

**Comment by RedFox20** [comment]
@roctobre The latest commits should have all the needed fixes. Now only games that are installed are considered as `CurrentGame` candidates.

**Comment by roctobre** [comment]
Now PFM starts. but it doesnt recognize Rome2 or Attila as installed games.

![grafik](https://user-images.githubusercontent.com/36789094/36646743-1c8dbe12-1a7c-11e8-80d9-978dbe98b57b.png)

**Comment by RedFox20** [comment]
Yeah, something is really weird with this. It's definitely not finding `S:\Spiele\Steam\steamapps\common\Total War Attila\data`

Does that folder exist? What filesystem does `S:\` have?

**Comment by roctobre** [comment]
NTFS. PFM 5.0 finds both folders btw.

![grafik](https://user-images.githubusercontent.com/36789094/36648086-f657f63c-1a8e-11e8-981d-c4bb44fe8f7a.png)

**Comment by roctobre** [comment]
Your latest change works.

And thanks to your version it seems the schema needs to be corrected for Rome2 "building_levels" and "building_units_allowed".

**Comment by RedFox20** [comment]
Great! Glad to see that this worked. The Schema is updated semi-manually by other people, so it's a little bit involved. I haven't properly configured auto-updates yet and SourceForge seems to be failing due to DDoS. The current schema in 5.1 is schema_108. Not sure when the next one will be available.
